/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai4;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author MSI-PC
 */
public class Alice extends javax.swing.JFrame {

    /**
     * Creates new form Alice
     */
    KeyAgreement aliceKeyAgree;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher aliceCipher;
    
    public Alice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkhoaa = new javax.swing.JTextField();
        txtkhoab = new javax.swing.JTextField();
        txtkhoachung = new javax.swing.JTextField();
        txtmahoakab = new javax.swing.JTextField();
        btnkhoaA = new javax.swing.JButton();
        btnkhoaB = new javax.swing.JButton();
        btnkhoaAB = new javax.swing.JButton();
        btnkhoakab = new javax.swing.JButton();
        btnmahoagiaima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Alice");

        jLabel2.setText("Khóa Alice:");

        jLabel3.setText("Khóa BoB:");

        jLabel4.setText("Khóa KAB:");

        jLabel5.setText("Mã hóa KAB:");

        btnkhoaA.setText("Tạo khóa A");
        btnkhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaAActionPerformed(evt);
            }
        });

        btnkhoaB.setText("Hiện thị KB");
        btnkhoaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaBActionPerformed(evt);
            }
        });

        btnkhoaAB.setText("Khóa Chung");
        btnkhoaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaABActionPerformed(evt);
            }
        });

        btnkhoakab.setText("Mã hóa KAB");
        btnkhoakab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoakabActionPerformed(evt);
            }
        });

        btnmahoagiaima.setText("Mã hóa/Giải mã");
        btnmahoagiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoagiaimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkhoaa)
                                    .addComponent(txtkhoab, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                    .addComponent(txtkhoachung)
                                    .addComponent(txtmahoakab))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnkhoaA)
                                    .addComponent(btnkhoaB)
                                    .addComponent(btnkhoaAB)
                                    .addComponent(btnkhoakab)))
                            .addComponent(btnmahoagiaima, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkhoaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoaA))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkhoab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnkhoaB))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkhoachung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnkhoaAB))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmahoakab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoakab))
                .addGap(43, 43, 43)
                .addComponent(btnmahoagiaima)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaAActionPerformed
        // TODO add your handling code here:
        try{
            AlgorithmParameterGenerator paramGen = AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params = paramGen.generateParameters();
            
            DHParameterSpec dhSkipParamSpec = (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);
            
            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator aliceKpairGen = KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKpair = aliceKpairGen.generateKeyPair();
            
            System.out.println("Initializing the KeyAgreement Engine with DH private key");
            aliceKeyAgree = KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());
            
            byte[] alicePubKeyEnc = aliceKpair.getPublic().getEncoded();
            FileOutputStream fos = new FileOutputStream("D:/A.pub");
            fos.write(alicePubKeyEnc);
            fos.close();
            txtkhoaa.setText(alicePubKeyEnc.toString());
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btnkhoaAActionPerformed

    private void btnkhoaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaBActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis = new FileInputStream("D:/B.pub");
            byte[] bkeyP = new byte[fis.available()];
            fis.read(bkeyP);
            fis.close();
            txtkhoab.setText(bkeyP.toString());
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoaBActionPerformed

    private void btnkhoaABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaABActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis = new FileInputStream("D:/B.pub");
            byte[] bobPubKeyEnc = new byte[fis.available()];
            fis.read(bobPubKeyEnc);
            fis.close();
            
            KeyFactory aliceKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(bobPubKeyEnc);
            bobPubKey = aliceKeyFac.generatePublic(x509KeySpec);
            System.out.println("Executing PHASE1 of key agreement...");
            aliceKeyAgree.doPhase(bobPubKey, true);
            byte[] aliceSharedSecret = aliceKeyAgree.generateSecret();
            
            System.out.println("Khoa chung: secret (DEBUG ONLY):" + CryptoUtil.toHexString(aliceSharedSecret));
            txtkhoachung.setText(CryptoUtil.toHexString(aliceSharedSecret));
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoaABActionPerformed

    private void btnkhoakabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoakabActionPerformed
        // TODO add your handling code here:
        try{
            aliceKeyAgree.doPhase(bobPubKey, true);
            aliceDesKey = aliceKeyAgree.generateSecret("DES");
            txtmahoakab.setText(aliceDesKey.toString());
            
            BufferedWriter bw = null;
            String fileName = "D:\\KhoaA.txt";
            
            bw = new BufferedWriter (new FileWriter(fileName));
            bw.write(aliceDesKey.toString());
            bw.close();
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoakabActionPerformed

    private void btnmahoagiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoagiaimaActionPerformed
        // TODO add your handling code here:
        DESCS des = new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btnmahoagiaimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkhoaA;
    private javax.swing.JButton btnkhoaAB;
    private javax.swing.JButton btnkhoaB;
    private javax.swing.JButton btnkhoakab;
    private javax.swing.JButton btnmahoagiaima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtkhoaa;
    private javax.swing.JTextField txtkhoab;
    private javax.swing.JTextField txtkhoachung;
    private javax.swing.JTextField txtmahoakab;
    // End of variables declaration//GEN-END:variables
}
